import React from "react";
import styled from "@emotion/styled";

const Loading = styled.div`
text-align:center;
@keyframes ldio-xj04k4g024 {
   0% { transform: translate(12px,80px) scale(0); }
  25% { transform: translate(12px,80px) scale(0); }
  50% { transform: translate(12px,80px) scale(1); }
  75% { transform: translate(80px,80px) scale(1); }
 100% { transform: translate(148px,80px) scale(1); }
}
@keyframes ldio-xj04k4g024-r {
   0% { transform: translate(148px,80px) scale(1): }
 100% { transform: translate(148px,80px) scale(0); }
}
@keyframes ldio-xj04k4g024-c {
   0% { background: #000000 }
  25% { background: #000000 }
  50% { background: #000000 }
  75% { background: #28292f }
 100% { background: #000000 }
}
.ldio-xj04k4g024 div {
  position: absolute;
  width: 40px;
  height: 40px;
  border-radius: 50%;
  transform: translate(80px,80px) scale(1);
  background: #000000;
  animation: ldio-xj04k4g024 1s infinite cubic-bezier(0,0.5,0.5,1);
}
.ldio-xj04k4g024 div:nth-child(1) {
  background: #28292f;
  transform: translate(148px,80px) scale(1);
  animation: ldio-xj04k4g024-r 0.25s infinite cubic-bezier(0,0.5,0.5,1), ldio-xj04k4g024-c 1s infinite step-start;
}.ldio-xj04k4g024 div:nth-child(2) {
  animation-delay: -0.25s;
  background: #000000;
}.ldio-xj04k4g024 div:nth-child(3) {
  animation-delay: -0.5s;
  background: #28292f;
}.ldio-xj04k4g024 div:nth-child(4) {
  animation-delay: -0.75s;
  background: #000000;
}.ldio-xj04k4g024 div:nth-child(5) {
  animation-delay: -1s;
  background: #000000;
}
.loadingio-spinner-ellipsis-pcubhivnvfr {
  width: 200px;
  height: 200px;
  display: inline-block;
  overflow: hidden;
  background: none;
}
.ldio-xj04k4g024 {
  width: 100%;
  height: 100%;
  position: relative;
  transform: translateZ(0) scale(1);
  backface-visibility: hidden;
  transform-origin: 0 0; /* see note above */
}
.ldio-xj04k4g024 div { box-sizing: content-box; }
/* generated by https://loading.io/ */
`;

const Loader = () => {
  return (
    <Loading>
      <div class="loadingio-spinner-ellipsis-pcubhivnvfr">
        <div class="ldio-xj04k4g024">
          <div></div>
          <div></div>
          <div></div>
          <div></div>
          <div></div>
        </div>
      </div>
    </Loading>
  );
};

export default Loader;
